core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static


admin.site.index_title='Library Management'
admin.site.site_header='Admin Dashboard' 


# 



urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    path('',include('library.urls')),
]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path
from .views import allbooks,search,addbook,deletebook,issuerequest,myissues,issue_book,return_book,requestedissues,myfines,allfines,deletefine,payfine,pay_status,sort
urlpatterns = [
    path('',allbooks,name='home'),
    path('search/',search),
    path('sort/',sort),
    path('addbook/',addbook),
    path('deletebook/<int:bookID>/',deletebook),
    path('request-book-issue/<int:bookID>/',issuerequest),
    path('my-issues/',myissues),
    path('my-fines/',myfines),
    path('payfines/<int:fineID>/',payfine),
    path('paystatus/<int:fineID>/',pay_status),
    path('all-issues/',requestedissues),
    path('all-fines/',allfines),
    path('issuebook/<int:issueID>/',issue_book),
    path('returnbook/<int:issueID>/',return_book),
    path('delete-fine/<int:fineID>/',deletefine),
]

library/models.py
from django.db import models
from student.models import Student
import datetime
from django.utils import timezone
# Create your models here.
class Author(models.Model):
    name=models.CharField(max_length=350)
    description=models.CharField(max_length=450)
    def __str__(self):
        return self.name
    
class Book(models.Model):
    name=models.CharField(max_length=350)
    author=models.ForeignKey(Author,on_delete=models.CASCADE)
    image=models.ImageField()
    category=models.CharField(max_length=220)

    def __str__(self):
        return self.name
    
class Issue(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE)
    book=models.ForeignKey(Book,on_delete=models.CASCADE)
    created_at=models.DateTimeField( auto_now_add=True)
    issued=models.BooleanField(default=False)
    issued_at=models.DateTimeField()
    returned=models.BooleanField(default=False)
    return_date=models.DateTimeField()

    def __str__(self):
        return "{}_{} book issue request".format(self.student,self.book)

    def days_no(self):
        "Returns the no. of days before returning / after return_date."
        if self.issued:
            y,m,d=str(timezone.now().date()).split('-')
            today=datetime.date(int(y),int(m),int(d))
            y2,m2,d2=str(self.return_date.date()).split('-')
            lastdate=datetime.date(int(y2),int(m2),int(d2))
            print(lastdate-today,lastdate>today)
            if lastdate > today:
                return "{} left".format(str(lastdate-today).split(',')[0])
            else:
                return "{} passed".format(str(today-lastdate).split(',')[0])
        else:
            return ""
    
class Fine(models.Model):
    student=models.ForeignKey(Student,on_delete=models.CASCADE)
    issue=models.ForeignKey(Issue,on_delete=models.CASCADE)
    amount=models.DecimalField(default=0.00,max_digits=10,decimal_places=2)
    paid=models.BooleanField(default=False)
    order_id = models.CharField(unique=True, max_length=500, null=True, blank=True, default=None) 
    datetime_of_payment = models.DateTimeField(auto_now=False,null=True,blank=True)
    
    # related to razorpay
    razorpay_order_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_payment_id = models.CharField(max_length=500, null=True, blank=True)
    razorpay_signature = models.CharField(max_length=500, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.order_id is None :
            self.order_id = "{}_{}_{}".format(self.student.department,self.student.student_id.username,timezone.now().strftime('%H%M%S') )  
        return super().save(*args, **kwargs)

    def __str__(self):
        return "{} fine->{}".format(self.issue,self.amount)

library/views.py
from django.shortcuts import render,redirect
from .models import Book,Author,Issue,Fine
from student.models import Student
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.utils import timezone
import datetime
from .utilities import calcFine,getmybooks
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import auth
from core import settings


# Book
def allbooks(request):
    requestedbooks,issuedbooks=getmybooks(request.user)
    allbooks=Book.objects.all()
    
    return render(request,'library/home.html',{'books':allbooks,'issuedbooks':issuedbooks,'requestedbooks':requestedbooks})


def sort(request):
    sort_type=request.GET.get('sort_type')
    sort_by=request.GET.get('sort')
    requestedbooks,issuedbooks=getmybooks(request.user)
    if 'author' in sort_type:
        author_results=Author.objects.filter(name__startswith=sort_by)
        return render(request,'library/home.html',{'author_results':author_results,'issuedbooks':issuedbooks,'requestedbooks':requestedbooks,'selected':'author'})
    else:
        books_results=Book.objects.filter(name__startswith=sort_by)
        return render(request,'library/home.html',{'books_results':books_results,'issuedbooks':issuedbooks,'requestedbooks':requestedbooks,'selected':'book'})


def search(request):
    search_query=request.GET.get('search-query')
    search_by_author=request.GET.get('author')
    requestedbooks,issuedbooks=getmybooks(request.user)

    if search_by_author is not None:
        author_results=Author.objects.filter(name__icontains=search_query)
        return render(request,'library/home.html',{'author_results':author_results,'issuedbooks':issuedbooks,'requestedbooks':requestedbooks})
    else:
        books_results=Book.objects.filter(Q(name__icontains=search_query) | Q(category__icontains=search_query))
        return render(request,'library/home.html',{'books_results':books_results,'issuedbooks':issuedbooks,'requestedbooks':requestedbooks})



@login_required(login_url='/student/login/')
@user_passes_test(lambda u: u.is_superuser,login_url='/student/login/')
def addbook(request):
    authors=Author.objects.all()
    if request.method=="POST":
        name=request.POST['name']
        category=request.POST['category']
        author=Author.objects.get(id=request.POST['author'])
        image=request.FILES['book-image']
        if author is not None or author != '':
            newbook,created=Book.objects.get_or_create(name=name,image=image,category=category,author=author)
            messages.success(request,'Book - {} Added succesfully '.format(newbook.name))
            return render(request,'library/addbook.html',{'authors':authors,})
        else:
            messages.error(request,'Author not found !')
            return render(request,'library/addbook.html',{'authors':authors,})
    else:
        return render(request,'library/addbook.html',{'authors':authors})



@login_required(login_url='/student/login/')
@user_passes_test(lambda u: u.is_superuser,login_url='/student/login/')
def deletebook(request,bookID):
    book=Book.objects.get(id=bookID)
    messages.success(request,'Book - {} Deleted succesfully '.format(book.name))
    book.delete()
    return redirect('/')



#  ISSUES

@login_required(login_url='/student/login/')
@user_passes_test(lambda u: not u.is_superuser,login_url='/student/login/')
def issuerequest(request,bookID):
    student=Student.objects.filter(student_id=request.user)
    if student:
        book=Book.objects.get(id=bookID)
        issue,created=Issue.objects.get_or_create(book=book,student=student[0])
        messages.success(request,'Book - {} Requested succesfully '.format(book.name))
        return redirect('home')
    
    messages.error(request,'You are Not a Student !')
    return redirect('/')

@login_required(login_url='/student/login/')
@user_passes_test(lambda u: not u.is_superuser ,login_url='/student/login/')
def myissues(request):
    if Student.objects.filter(student_id=request.user):
        student=Student.objects.filter(student_id=request.user)[0]
        
        if request.GET.get('issued') is not None:
            issues=Issue.objects.filter(student=student,issued=True)
        elif request.GET.get('notissued') is not None:
            issues=Issue.objects.filter(student=student,issued=False)
        else:
            issues=Issue.objects.filter(student=student)

        return render(request,'library/myissues.html',{'issues':issues})
    
    messages.error(request,'You are Not a Student !')
    return redirect('/')


@login_required(login_url='/admin/')
@user_passes_test(lambda u:  u.is_superuser ,login_url='/admin/')
def requestedissues(request):
    if request.GET.get('studentID') is not None and request.GET.get('studentID') != '':
        try:
            user= User.objects.get(username=request.GET.get('studentID'))
            student=Student.objects.filter(student_id=user)
            if student:
                student=student[0]
                issues=Issue.objects.filter(student=student,issued=False)
                return render(request,'library/allissues.html',{'issues':issues})
            messages.error(request,'No Student found')
            return redirect('/all-issues/') 
        except User.DoesNotExist:
            messages.error(request,'No Student found')
            return redirect('/all-issues/')

    else:
        issues=Issue.objects.filter(issued=False)
        return render(request,'library/allissues.html',{'issues':issues})



@login_required(login_url='/admin/')
@user_passes_test(lambda u:  u.is_superuser ,login_url='/student/login/')
def issue_book(request,issueID):
    issue=Issue.objects.get(id=issueID)
    issue.return_date=timezone.now() + datetime.timedelta(days=15)
    issue.issued_at=timezone.now()
    issue.issued=True
    issue.save()
    return redirect('/all-issues/')


@login_required(login_url='/student/login/')
@user_passes_test(lambda u:  u.is_superuser ,login_url='/admin/')
def return_book(request,issueID):
    issue=Issue.objects.get(id=issueID)
    calcFine(issue)
    issue.returned=True
    issue.save()
    return redirect('/all-issues/')


#  FINES

@login_required(login_url='/student/login/')
@user_passes_test(lambda u: not u.is_superuser ,login_url='/student/login/')
def myfines(request):
    if Student.objects.filter(student_id=request.user):
        student=Student.objects.filter(student_id=request.user)[0]
        issues=Issue.objects.filter(student=student)
        for issue in issues:
            calcFine(issue)
        fines=Fine.objects.filter(student=student)
        return render(request,'library/myfines.html',{'fines':fines})
    messages.error(request,'You are Not a Student !')
    return redirect('/')


@login_required(login_url='/student/login/')
@user_passes_test(lambda u:  u.is_superuser ,login_url='/admin/')
def allfines(request):
    issues=Issue.objects.all()
    for issue in issues:
        calcFine(issue)
    return redirect('/admin/library/fine/')

@login_required(login_url='/student/login/')
@user_passes_test(lambda u:  u.is_superuser ,login_url='/admin/')
def deletefine(request,fineID):
    fine=Fine.objects.get(id=fineID)
    fine.delete()
    return redirect('/all-fines/')

import razorpay
razorpay_client = razorpay.Client(auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))

@login_required(login_url='/student/login/')
@user_passes_test(lambda u: not u.is_superuser ,login_url='/student/login/')
def payfine(request,fineID):
    fine=Fine.objects.get(id=fineID)
    order_amount = int(fine.amount)*100
    order_currency = 'INR'
    order_receipt = fine.order_id
    
    
    razorpay_order=razorpay_client.order.create(dict(amount=order_amount, currency=order_currency, receipt=order_receipt, ))
    print(razorpay_order)
    
    
    return render(request,'library/payfine.html',
    {'amount':order_amount,'razor_id':settings.RAZORPAY_KEY_ID,
    'reciept':razorpay_order['id'],
    'amount_displayed':order_amount / 100,
    'address':'a custom address',
    'fine':fine, 
    })


@login_required(login_url='/student/login/')
@user_passes_test(lambda u: not u.is_superuser ,login_url='/student/login/')
def pay_status(request,fineID):
    if request.method == 'POST':
        params_dict={
            'razorpay_payment_id':request.POST['razorpay_payment_id'],
            'razorpay_order_id':request.POST['razorpay_order_id'],
            'razorpay_signature':request.POST['razorpay_signature'],
        }
        try:
            status=razorpay_client.utility.verify_payment_signature(params_dict)
            if status is None:
                fine=Fine.objects.get(id=fineID)
                fine.paid=True
                fine.datetime_of_payment=timezone.now()
                fine.razorpay_payment_id=request.POST['razorpay_payment_id']
                fine.razorpay_signature=request.POST['razorpay_signature']
                fine.razorpay_order_id = request.POST['razorpay_order_id']
                fine.save()
                
            messages.success(request,'Payment Succesfull')
        except:
            messages.error(request,'Payment Failure')
    return redirect('/my-fines/')

templates/library/addbook.html
{% extends 'base.html' %} {% block heading %} Add Book {% endblock heading %}
<!--  -->
{% block content %}

<form
  class="w-2xl sm:w-1/2 max-w-lg flex flex-col mx-auto"
  method="POST"
  action="/addbook/"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="name">Name</label>
    <input
      class="px-2 py-1 bg-transparent border-white border-2 rounded text-gray-800"
      type="text"
      placeholder="name"
      name="name"
    />
  </div>
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="category">Category</label>
    <input
      class="px-2 py-1 bg-transparent border-white border-2 rounded text-gray-800"
      type="text"
      placeholder="category"
      name="category"
    />
  </div>
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="book-image">Image</label>
    <input
      class="px-2 py-1 bg-transparent border-white border-2 rounded text-gray-800"
      type="file"
      accept="image/*"
      name="book-image"
    />
  </div>
  <div class="w-full max-w-lg flex flex-col mt-4 justify-center">
    <label class="text-xl mb-2" for="author">Author</label>
    <select
      class="rounded border border-red-300 py-2 focus:outline-none focus:ring-2 focus:ring-red-200 focus:border-red-500 text-base pl-3 pr-10 text-gray-800"
      name="author"
    >
      <option value="">Choose Author</option>
      {%for author in authors %}
      <option value="{{author.id}}">{{author.name}}</option>
      {% endfor %}
    </select>
  </div>
  <button
    class="text-white place-self-center hover:shadow-md text-xl w-full rounded bg-pink-500 px-4 py-1 mt-8"
    type="submit"
  >
    Add Book
  </button>
</form>
{% endblock content%}

templates/library/allfines.html
{% extends 'base.html' %} {% block heading %} All Fines {% endblock heading %}
{% block content %}
<form
  class="w-full flex flex-col sm:flex-row sm:items-center"
  action="/all-fines/"
>
  <label class="text-lg" for="studentID">Search Student : </label>
  <input
    class="w-full sm:w-1/3 px-2 py-1 bg-transparent border-white border-2 mt-4 sm:mt-0 sm:mx-5 rounded text-white placeholder-gray-700"
    type="text"
    name="studentID"
    id="search"
    placeholder="student id only"
  />
  <button
    class="text-white hover:shadow-md rounded mt-4 sm:mt-0 bg-blue-500 px-4 py-1"
  >
    Search
  </button>
</form>

<ul class="list-disc px-4 mt-8 space-y-4">
  {% for fine in fines %}
  <li>
    <h3 class="text-lg tracking-wide">
      Fine for
      <a
        target="_blank"
        href="/admin/student/student/{{fine.student.id}}/"
        class="font-bold hover:underline"
        >{{fine.student.student_id.username}} - {{fine.student.first_name}}</a
      >'s Issue {{fine.issue.id}}
    </h3>
    <h3 class="text-md mb-4">
      Amount: <span class="font-bold text-lg">₹{{fine.amount}}</span>
    </h3>
    <a
      class="text-white hover:shadow-md rounded bg-red-500 px-4 py-1"
      href="/delete-fine/{{fine.id}}"
      >Delete</a
    >
  </li>

  {% empty %}
  <h2>Nothing Found</h2>
  {% endfor %}
</ul>
{% endblock %}

templates/library/allissues.html
{% extends 'base.html' %} {% block heading %} All Issues {% endblock heading %}
{% block content %}
<form
  class="w-full flex flex-col sm:flex-row sm:items-center"
  action="/all-issues/"
>
  <label class="text-lg" for="studentID">Search Student :</label>
  <input
    class="w-full sm:w-1/3 px-2 py-1 bg-transparent border-white border-2 mt-4 sm:mt-0 sm:mx-5 rounded text-white placeholder-gray-700"
    type="text"
    name="studentID"
    id="search"
    placeholder="student id only"
  />
  <button
    class="text-white hover:shadow-md rounded mt-4 sm:mt-0 bg-blue-500 px-4 py-1"
  >
    Search
  </button>
</form>

<!--  -->
<ul class="list-disc px-4 mt-8">
  {% for issue in issues %}
  <li>
    <h3 class="text-xl tracking-wide">
      <span class="font-bold">{{issue.book.name}}</span> Issue Requested by
      <a
        target="_blank"
        href="/admin/student/student/{{issue.student.id}}/"
        class="font-bold hover:underline"
      >
        {{issue.student.student_id.username}}_{{issue.student.first_name}}</a
      >
    </h3>
    <h4 class="text-xs">Created at:-{{issue.created_at}}</h4>
    <div class="flex flex-row w-2/3 space-x-4 mt-4 mb-8">
      {% if user.is_superuser %} {% if issue.issued %}
      <h5 class="w-xs rounded text-md font-bold text-green-500 px-4 py-1">
        Issued
      </h5>
      {%if issue.returned %}
      <h5 class="w-xs rounded font-bold text-green-500 px-4 py-1">Returned</h5>
      {% else %}
      <a
        class="w-xs rounded bg-green-500 px-4 py-1 text-white"
        href="/returnbook/{{issue.id}}/"
        >return book</a
      >
      {% endif %} {% else %}
      <a
        class="w-xs rounded bg-blue-500 px-4 py-1 text-white"
        href="/issuebook/{{issue.id}}/"
        >issue book</a
      >
      {% endif %} {% endif %}
    </div>
  </li>
  {% empty %}
  <h2>Nothing Found</h2>
  {% endfor %}
</ul>

{% endblock %}

templates/library/home.html
{% extends 'base.html' %} {% block heading %} Books List {% endblock heading %}
<!--  -->
{% block content %}
<!-- searchbar -->
<form class="flex sm:flex-row flex-col" action="/search/">
  <div
    class="w-full md:w-1/2 l:w-1/3 flex flex-col sm:flex-row sm:items-center"
  >
    <label class="text-lg" for="search-query">Search :</label>
    <input
      class="w-full sm:w-2/3 px-2 py-1 bg-transparent border-white border-2 mt-4 sm:mt-0 sm:ml-10 rounded text-white"
      type="text"
      name="search-query"
      id="search"
    />
  </div>
  <div class="flex space-x-4 mt-4 sm:mt-0 flex-row sm:items-center">
    <button
      class="text-white hover:shadow-md rounded bg-blue-600 px-4 py-1 text-gray-100"
      name="author"
    >
      Author
    </button>
    <button
      class="hover:shadow-md bg-yellow-400 text-gray-900 rounded px-4 py-1"
      name="book"
    >
      Book
    </button>
  </div>
</form>
<!-- sorting alphabetically -->
<form
  class="flex flex-col sm:flex-row sm:space-x-4 mt-8 sm:items-center"
  action="/sort/"
>
  <h3>Sort :</h3>
  <select
    class="rounded focus:outline-none focus:ring-2 focus:ring-red-200 focus:border-red-500 text-base pr-3 pl-1 text-gray-900"
    name="sort_type"
    id="sort_type"
  >
    <option value="book">book</option>
    <option value="author">author</option>
  </select>
  <ul id="sortable" class="flex flex-wrap space-x-1">
    <li><button name="sort" value="A">A</button></li>
    <li><button name="sort" value="B">B</button></li>
    <li><button name="sort" value="C">C</button></li>
    <li><button name="sort" value="D">D</button></li>
    <li><button name="sort" value="E">E</button></li>
    <li><button name="sort" value="F">F</button></li>
    <li><button name="sort" value="G">G</button></li>
    <li><button name="sort" value="H">H</button></li>
    <li><button name="sort" value="I">I</button></li>
    <li><button name="sort" value="J">J</button></li>
    <li><button name="sort" value="K">K</button></li>
    <li><button name="sort" value="L">L</button></li>
    <li><button name="sort" value="M">M</button></li>
    <li><button name="sort" value="N">N</button></li>
    <li><button name="sort" value="O">O</button></li>
    <li><button name="sort" value="P">P</button></li>
    <li><button name="sort" value="Q">Q</button></li>
    <li><button name="sort" value="R">R</button></li>
    <li><button name="sort" value="S">S</button></li>
    <li><button name="sort" value="T">T</button></li>
    <li><button name="sort" value="U">U</button></li>
    <li><button name="sort" value="V">V</button></li>
    <li><button name="sort" value="W">W</button></li>
    <li><button name="sort" value="X">X</button></li>
    <li><button name="sort" value="Y">Y</button></li>
    <li><button name="sort" value="Z">Z</button></li>
  </ul>
</form>
<!-- all books -->
<ul
  class="mt-10 md:px-4 lg:px-12 xl:px-0 grid grid-cols-1 md:grid-cols-3 xl:grid-cols-4"
>
  {% for book in books %}
  <li class="mb-12 md:mb-4 mx-auto text-center">
    <h2 class="text-lg font-bold">{{book.name}}</h2>
    <h4 class="text-xs font-regular text-blue-500 pt-2">{{book.author}}</h4>
    <h4 class="text-sm pb-2 text-yellow-300">{{book.category}}</h4>
    <div class="grid place-items-center p-2">
      <img
        src="{{book.image.url}}"
        alt="{{book.name}}"
        height="100"
        width="100"
        class="mb-4"
      /><hr>
    </div>
    {% if not user.is_superuser and not user.is_anonymous %}
    <!--  -->

    {% if book in issuedbooks %}
    <p class="text-green-500 font-medium">issued</p>
    {% elif book in requestedbooks %}
    <p class="font-medium">issued requested</p>
    {% else %}

    <a
      class="text-white hover:shadow-md rounded bg-pink-600 px-4 py-1"
      href="/request-book-issue/{{book.id}}/"
      >Request Issue</a
    >
    {% endif %} {% endif %} {% if user.is_superuser %}
    <a
      href="/admin/library/book/{{book.id}}/change/"
      class="text-white hover:shadow-md rounded bg-pink-600 px-4 py-1"
      >Edit</a
    >
    {% endif %}
  </li>

  {% endfor %}
</ul>

<!-- author search results -->
{% if 'author' in request.get_full_path %} {% for author in author_results %}

<div {% if not forloop.first %} class="my-8" {% endif %}>
  <h1 class="text-lg font-bold mb-2">{{author.name}}</h1>

  <ul class="list-disc px-4">
    {% for book in author.book_set.all %}
    <li>
      <div class="flex flex-row space-x-4">
        <h2>{{book.name}}</h2>
        {% if not user.is_superuser and not user.is_anonymous %}
        <!--  -->
        {% if book in issuedbooks %}
        <p class="text-green-500 font-medium">issued</p>
        {% elif book in requestedbooks %}
        <p class="text-pink-500 font-medium">issued requested</p>
        {% else %}
        <a
          class="hover:shadow-md rounded text-blue-500 underline"
          href="/request-book-issue/{{book.id}}/"
          >Request Issue</a
        >
        {% endif %} {% endif %}
      </div>
    </li>

    {%empty %}
    <h2>No Books</h2>
    {% endfor %}
  </ul>
</div>
{%empty %}
<h2>Not Found</h2>
{% endfor %} {% endif %}
<!-- book results -->
{% if 'book' in request.get_full_path %}
<ul
  class="mt-10 md:px-4 lg:px-12 xl:px-0 grid grid-cols-2 md:grid-cols-4 justify-items-center"
>
  {% for book in books_results %}
  <li class="px-2">
    <h2 class="text-md font-bold">{{book.name}}</h2>
    <h4 class="text-sm">{{book.author}}</h4>
    <img
      src="{{book.image.url}}"
      alt="{{book.name}}"
      height="80"
      width="80"
      class="mb-4"
    />
    {% if not user.is_superuser and not user.is_anonymous %}
    <!--  -->
    {% if book in issuedbooks %}
    <p class="text-green-500 font-medium">issued</p>
    {% elif book in requestedbooks %}
    <p class="text-pink-500 font-medium">issued requested</p>
    {% else %}
    <a
      class="hover:shadow-md rounded text-blue-500 underline"
      href="/request-book-issue/{{book.id}}/"
      >Request Issue</a
    >
    {% endif %} {% endif %} {% if user.is_superuser %}
    <a
      href="/admin/library/book/{{book.id}}/change/"
      class="text-white hover:shadow-md rounded bg-blue-500 px-4 py-1"
      >Edit</a
    >
    {% endif %}
  </li>
  {%empty %}
  <h2>No Books Found</h2>
  {% endfor %}
</ul>
{% endif %}
<script>
  const options = document.querySelectorAll("#sort_type option");
  options.forEach((option) => {
    if (option.textContent === "{{selected | escapejs}}") {
      option.selected = true;
    }
  });
</script>
{% endblock content %}

templates/library/myfines.html
{% extends 'base.html' %} {%block heading %} My Fines {% endblock heading %}
<!--  -->
{%block content %}
<ul class="list-disc px-4">
  {% for fine in fines %}
  <li>
    <div class="flex flex-col sm:flex-row content-center">
      <h2 class="mt-0 sm:mt-2">
        Fine of
        <span class="text-black text-red-500">₹{{fine.amount}}</span> for Book
        :- {{fine.issue.book.name}}
      </h2>
      {%if fine.paid %}
      <p class="text-white hover:shadow-md text-md rounded text-center bg-green-700 px-4 py-1 mt-2 sm:mt-0 ml-0 sm:ml-2">Paid on {{fine.datetime_of_payment}}</p>
      {% else %}
      <a
        class="text-white hover:shadow-md text-md rounded text-center bg-purple-600 px-4 py-2 mt-2 sm:mt-0 ml-0 sm:ml-2"
        href="/payfines/{{fine.id}}/"
        >Pay</a
      >
      {% endif %}
    </div>
  </li>
  {% endfor %}
</ul>
{% endblock content %}

templates/library/paystatus.html
<h1>Some unknown error occurred !</h1>